### ISSUE TITLE
a bit of Matlab debugging 

### ISSUE THREAD

**Issue by mmyros** [PulsePal/PulsePal#2]
I think my experience might be helpful for other people. Python interface was working for me, but Matlab was not. I followed steps outlined here to get it to work:
http://www.mathworks.com/matlabcentral/answers/25323-using-serial-to-connect-to-an-arduino

Briefly, I had to tell Java that ttyACM0 is available and create java.opts file in the startup directory like so:
echo '-Dgnu.io.rxtx.SerialPorts=/dev/ttyS0:/dev/ttyS1:/dev/USB0:/dev/ttyACM0'>java.opts

**Comment by PulsePal** [comment]
Hi mmyros

Thanks for the feedback!
The steps to make a port alias were also available on the Pulse Pal Wiki, on the setup page for Linux:
https://sites.google.com/site/pulsepalwiki/installing-pulse-pal/linux
Please see the subsection "Create an alias to the Pulse Pal serial port".

The option to add a java.opts file allows this alias to be permanent. I'll add those instructions to the Wiki now. 

For future improvements and feedback, I have also set up a support forum:
http://pulsepal.bbforum.co/

Regards,
Josh Sanders
