### ISSUE TITLE
abort button in matlab GUI

### ISSUE THREAD

**Issue by lepmik** [PulsePal/PulsePal#3]
It would be nice to be able to stop the current pulse train

**Comment by PulsePal** [comment]
You have 4 options for stopping the ongoing pulse train: 
1. (stand-alone mode) click the thumb joystick at any time
2. (MATLAB): https://sites.google.com/site/pulsepalwiki/using-pulse-pal/functions/abortpulsepal
3. (Python): https://sites.google.com/site/pulsepalwiki/user-guide---python/python-methods/abortpulsetrains
   4: (C++): https://sites.google.com/site/pulsepalwiki/user-guide---c-api/c-methods/abortpulsetrains

The official support forum for Pulse Pal is here:
https://sites.google.com/site/pulsepalwiki/forum
